<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>cd0935cf-1dce-4462-a1f2-151a5ee3f80e</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

	<ItemGroup>
		<Compile Remove="Configuration\Middleware\**" />
		<Content Remove="$(NuGetPackageRoot)**\BuildHost-net472\**;$(NuGetPackageRoot)**\BuildHost-netcore\**" />
		<Content Remove="Configuration\Middleware\**" />
		<EmbeddedResource Remove="Configuration\Middleware\**" />
		<None Remove="$(NuGetPackageRoot)**\BuildHost-net472\**;$(NuGetPackageRoot)**\BuildHost-netcore\**" />
		<None Remove="Configuration\Middleware\**" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="EmailTemplates\Messages\Welcome.html" />
	  <None Remove="EmailTemplates\_Layout.html" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include="EmailTemplates\Messages\Welcome.html">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Include="EmailTemplates\_Layout.html">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>


	<ItemGroup>
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
    <PackageReference Include="HtmlSanitizer" Version="9.0.889" />
    <PackageReference Include="Markdig" Version="0.44.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.OpenApi" Version="2.3.0" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WitcherHub.Application\WitcherHub.Application.csproj" />
    <ProjectReference Include="..\WitcherHub.Infrastructure\WitcherHub.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="OpenAI\Contracts\" />
    <Folder Include="Resources\Pages\" />
    <Folder Include="wwwroot\theme\assets\" />
  </ItemGroup>

</Project>
