using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using WitcherHub.Application.Common.CacheKeys;
using WitcherHub.Application.Common.Caching;
using WitcherHub.Application.Common.Exceptions;
using WitcherHub.Application.Interfaces;
using WitcherHub.Application.Interfaces.ManageData;
using WitcherHub.Infrastructure.Data.Models;
using static WitcherHub.Infrastructure.Data.Models.Enums;

namespace WitcherHub.Infrastructure.ManageData.Payments
{
    /// <summary>
    /// Recording money received against an invoice.
    ///
    /// The schema has always had somewhere to put this — a Payment table, and
    /// PaidTotal/BalanceDue on InvoiceTotal — and the invoice totals calculation
    /// already sums payments. Nothing ever wrote a Payment row, so the balance on
    /// every invoice was its full amount forever, and the only way a paid invoice
    /// could show as paid was through the Lexware sync overwriting the totals
    /// directly.
    /// </summary>
    public sealed class ManagePayments : IPayments
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IAppCache _cache;
        private readonly ILogger<ManagePayments> _log;

        public ManagePayments(IUnitOfWork unitOfWork, IAppCache cache, ILogger<ManagePayments> log)
        {
            _unitOfWork = unitOfWork;
            _cache = cache;
            _log = log;
        }

        public async Task<PaymentResult> RecordAsync(RecordPaymentDto dto, CancellationToken ct = default)
        {
            if (dto.InvoiceId == Guid.Empty)
                throw new BadRequestAppException("Invalid invoice id.");

            if (dto.Amount <= 0m)
                throw new BadRequestAppException("A payment must be greater than zero.");

            // A payment dated in the future has almost always been mistyped, and it
            // would silently distort "collected this month".
            var today = DateOnly.FromDateTime(DateTime.UtcNow);
            if (dto.ReceivedOn > today)
                throw new BadRequestAppException("A payment cannot be dated in the future.");

            var invoiceRepo = _unitOfWork.Repo<Invoice>();

            var invoice = await invoiceRepo.Query(asNoTracking: false)
                .Include(x => x.Items)
                .Include(x => x.Totals)
                .FirstOrDefaultAsync(x => x.Id == dto.InvoiceId, ct)
                ?? throw new NotFoundAppException("Invoice not found.");

            if (invoice.Status is DocumentStatus.Draft)
                throw new BadRequestAppException(
                    "This invoice is still a draft. Issue it before recording a payment against it.");

            if (invoice.Status is DocumentStatus.Void or DocumentStatus.Cancelled)
                throw new BadRequestAppException(
                    "This invoice has been cancelled, so a payment cannot be recorded against it.");

            var payment = new Payment
            {
                Id = Guid.NewGuid(),
                InvoiceId = invoice.Id,
                Amount = decimal.Round(dto.Amount, 2, MidpointRounding.AwayFromZero),
                Currency = invoice.Currency,
                Method = dto.Method,
                Status = dto.Status,
                ProviderRef = string.IsNullOrWhiteSpace(dto.Reference) ? null : dto.Reference.Trim(),

                // Stored as a moment because that is the column's type, but the day
                // is what was entered: a bank statement gives a date, not a time.
                PaidAt = dto.Status == PaymentStatus.Success
                    ? new DateTimeOffset(dto.ReceivedOn.ToDateTime(TimeOnly.MinValue), TimeSpan.Zero)
                    : null
            };

            // Inserted explicitly rather than by adding it to invoice.Payments.
            // A Guid key is store-generated by convention, so an entity that
            // arrives in a tracked graph already carrying one is taken to be an
            // existing row: EF marked the new payment Modified and issued an
            // UPDATE against a row that did not exist yet.
            await _unitOfWork.Repo<Payment>().AddAsync(payment, ct);
            await _unitOfWork.SaveChangesAsync(ct);

            var result = await ApplyPaymentsToInvoiceAsync(invoice, ct);

            _log.LogInformation(
                "Recorded a {Method} payment of {Amount} {Currency} against invoice {InvoiceNo}. " +
                "Balance is now {Balance}.",
                payment.Method, payment.Amount, payment.Currency, invoice.InvoiceNo, result.BalanceDue);

            return result with { PaymentId = payment.Id };
        }

        public async Task<PaymentResult> DeleteAsync(Guid paymentId, CancellationToken ct = default)
        {
            var paymentRepo = _unitOfWork.Repo<Payment>();

            var payment = await paymentRepo.Query(asNoTracking: false)
                .FirstOrDefaultAsync(x => x.Id == paymentId, ct)
                ?? throw new NotFoundAppException("Payment not found.");

            var invoiceId = payment.InvoiceId;
            paymentRepo.Remove(payment);
            await _unitOfWork.SaveChangesAsync(ct);

            var invoice = await _unitOfWork.Repo<Invoice>().Query(asNoTracking: false)
                .Include(x => x.Items)
                .Include(x => x.Totals)
                .FirstOrDefaultAsync(x => x.Id == invoiceId, ct)
                ?? throw new NotFoundAppException("Invoice not found.");

            var result = await ApplyPaymentsToInvoiceAsync(invoice, ct);

            _log.LogWarning(
                "Removed a payment of {Amount} {Currency} from invoice {InvoiceNo}. Balance is now {Balance}.",
                payment.Amount, payment.Currency, invoice.InvoiceNo, result.BalanceDue);

            return result with { PaymentId = paymentId };
        }

        public async Task<IReadOnlyList<PaymentRow>> GetForInvoiceAsync(Guid invoiceId, CancellationToken ct = default)
        {
            return await _unitOfWork.Repo<Payment>().Query(asNoTracking: true)
                .Where(p => p.InvoiceId == invoiceId)
                .OrderByDescending(p => p.PaidAt ?? p.CreatedAt)
                .Select(p => new PaymentRow
                {
                    Id = p.Id,
                    Amount = p.Amount,
                    Currency = p.Currency,
                    Method = p.Method,
                    Status = p.Status,
                    Reference = p.ProviderRef,
                    PaidAt = p.PaidAt,
                    RecordedAt = p.CreatedAt
                })
                .ToListAsync(ct);
        }

        /// <summary>
        /// Recomputes the paid total and balance from the payments that actually
        /// count, and moves the invoice's status if the balance has cleared.
        /// </summary>
        private async Task<PaymentResult> ApplyPaymentsToInvoiceAsync(Invoice invoice, CancellationToken ct)
        {
            // Read back from the database rather than from invoice.Payments.
            // The navigation collection is populated both by the Include and by
            // EF's relationship fix-up, so a freshly added payment can appear in
            // it twice and count double against the balance.
            //
            // Only settled money reduces the balance. The existing totals
            // calculation summed every payment row regardless of status, so a
            // pending or failed payment would have marked the invoice paid.
            var settled = _unitOfWork.Repo<Payment>().Query(asNoTracking: true)
                .Where(p => p.InvoiceId == invoice.Id && p.Status == PaymentStatus.Success);

            var paidTotal = await settled.SumAsync(p => (decimal?)p.Amount, ct) ?? 0m;

            var total = invoice.Totals?.Total
                        ?? invoice.Items.Sum(i => i.Quantity * i.UnitPrice);

            var balanceDue = Math.Max(0m, total - paidTotal);

            invoice.Totals ??= new InvoiceTotal { InvoiceId = invoice.Id, Total = total };

            invoice.Totals.PaidTotal = paidTotal;
            invoice.Totals.BalanceDue = balanceDue;
            invoice.Totals.UpdatedAt = DateTimeOffset.UtcNow;

            var isNowPaid = total > 0m && balanceDue == 0m;

            if (isNowPaid && invoice.Status != DocumentStatus.Paid)
            {
                invoice.Status = DocumentStatus.Paid;
                invoice.PaidAt = await settled.MaxAsync(p => p.PaidAt, ct);
            }
            else if (!isNowPaid && invoice.Status == DocumentStatus.Paid)
            {
                // A payment was removed or reversed. Fall back to whether the due
                // date has passed rather than leaving the invoice marked paid.
                invoice.Status = invoice.DueDate is not null &&
                                 invoice.DueDate < DateOnly.FromDateTime(DateTime.UtcNow)
                    ? DocumentStatus.Overdue
                    : DocumentStatus.Open;

                invoice.PaidAt = null;
            }

            await _unitOfWork.SaveChangesAsync(ct);

            await _cache.RemoveAsync(InvoiceCacheKeys.Details(invoice.Id), ct);
            await _cache.BumpVersionAsync(InvoiceCacheKeys.ListVersionKey, ct);

            return new PaymentResult(Guid.Empty, total, paidTotal, balanceDue, isNowPaid);
        }
    }
}
